### ISSUE TITLE
app stops when sending message with api rest example

### ISSUE THREAD

**Issue by diazzaid** [wppconnect-team/wppconnect#367] opened 2021-07-28 00:18 UTC
i try https://github.com/wppconnect-team/wppconnect/tree/master/examples/rest
the app closes when trying to send a message to an unregistered number
![image](https://user-images.githubusercontent.com/25816482/127243391-8b1f6742-3acd-4b0a-9a4c-94c40259fa30.png)
how to disable the number check feature or so that the application does not close when sending messages to unregistered numbers

**Comment by felipeloss** [comment] 2021-07-28 16:07
i have the same issue here

**Comment by claudioscarpafilho** [comment] 2021-07-28 16:47
I have similar issue here. 

Until 1.8.5 it´s ok. 
When i update to 1.8.9 starts this issue.

**Comment by leobevi** [comment] 2021-07-29 00:06
Yes there is an problem with the checkNumberStatus returning when it is an invalid number in this new update

**Comment by diazzaid** [comment] 2021-07-29 00:50
> I have similar issue here.
> 
> Until 1.8.5 it´s ok.
> When i update to 1.8.9 starts this issue.
> 
> ![image](https://user-images.githubusercontent.com/86273544/127363280-63636fa9-e4e2-4e97-a791-a88e7a69c1d5.png)

ohhh. i tried version 1.8.5 and it works

**Comment by leobevi** [comment] 2021-07-29 00:53
yes previous version works

**Comment by diazzaid** [comment] 2021-07-31 00:07
done with https://github.com/wppconnect-team/wppconnect/commit/2f289450c5b49349edc9936fd331c44b3d650f63
![image](https://user-images.githubusercontent.com/25816482/127722315-9665cccd-24e3-4cd0-b322-8a76292696f6.png)

**Comment by edgardmessias** [comment] 2021-07-31 00:25
I fixed it, I will release a new version today: duplicate of #372

**Closed by edgardmessias** 2021-07-31 00:25 UTC
Labels: question

**Comment by diazzaid** [comment] 2021-07-31 00:40
> I fixed it, I will release a new version today: duplicate of #372

can you help me for this api code
![image](https://user-images.githubusercontent.com/25816482/127723296-1db8e70e-e64c-428d-97f2-23975bde933e.png)
because after I tried the message was sent successfully but the app closed

**Comment by diazzaid** [comment] 2021-07-31 00:43
code 
https://github.com/wppconnect-team/wppconnect/blob/master/examples/rest/index.js

**Comment by diazzaid** [comment] 2021-07-31 00:52
> > I fixed it, I will release a new version today: duplicate of #372
> 
> can you help me for this api code
> ![image](https://user-images.githubusercontent.com/25816482/127723296-1db8e70e-e64c-428d-97f2-23975bde933e.png)
> because after I tried the message was sent successfully but the app closed

the language has been revised, but it still doesn't work
![image](https://user-images.githubusercontent.com/25816482/127723596-39452453-b18a-44e5-a124-673b07e7f467.png)

**Comment by diazzaid** [comment] 2021-07-31 02:10
ok .. work.. update to 1.8.10
